sistema_salud/citas/urls.py
from django.urls import path
from . import views

app_name = 'citas'

urlpatterns = [
    path('citas/', views.citas_view, name='citas'), 
    path('paciente/citas/', views.lista_citas_paciente, name='lista_citas_paciente'),
    path('paciente/agendar/', views.agendar_cita, name='agendar_cita'),
    path('profesional/citas/', views.lista_citas_profesional, name='lista_citas_profesional'),
    path('cambiar_estado/<int:cita_id>/<str:nuevo_estado>/', views.cambiar_estado_cita, name='cambiar_estado_cita'),
    path('agendar-cita/<str:profesional>/', views.agendar_cita, name='agendar_cita'),
  
]

sistema_salud/sistema_salud/urls.py
# sistema_salud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from usuarios.views import home  # Asegúrate de importar la vista home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),  # Ruta para la página de inicio
    path('usuarios/', include('usuarios.urls')),  # App de usuarios
    path('citas/', include('citas.urls')), # App de citas
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema_salud/citas/models.py
from django.db import models
from usuarios.models import CustomUser
from datetime import datetime, timedelta
import datetime as dt


class CitaManager(models.Manager):
    def pendientes(self):
        """Devuelve todas las citas pendientes."""
        return self.filter(estado_cita='pendiente')

    def confirmadas(self):
        """Devuelve todas las citas confirmadas."""
        return self.filter(estado_cita='confirmada')

    def canceladas(self):
        """Devuelve todas las citas canceladas."""
        return self.filter(estado_cita__in=[
            'cancelada_paciente', 'cancelada_profesional'
        ])


class Cita(models.Model):
    ESTADO_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('confirmada', 'Confirmada'),
        ('completada','Completada'),
        ('cancelada_paciente', 'Cancelada por el Paciente'),
        ('cancelada_profesional', 'Cancelada por el Profesional'),
    ]

    paciente = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='citas_paciente')
    profesional = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='citas_profesional')
    fecha = models.DateField()
    descripcion = models.TextField(blank=True)
    hora_inicio = models.CharField(max_length=10)  # Formato HH:MM
    es_bloqueado = models.BooleanField(default=False)
    duracion = models.IntegerField()  # Duración de la cita en minutos
    estado_cita = models.CharField(max_length=50, choices=ESTADO_CHOICES, default='pendiente')
    notas = models.TextField(blank=True, null=True)

    objects = CitaManager()  # Usar el manager personalizado

    def __str__(self):
        return f'Cita {self.id} - {self.paciente.full_name} con {self.profesional.full_name}'

    @property
    def hora_fin(self):
        """Calcula la hora de finalización de la cita."""
        hora_inicio_obj = dt.datetime.strptime(self.hora_inicio, '%H:%M').time()
        return (datetime.combine(self.fecha, hora_inicio_obj) + timedelta(minutes=self.duracion)).time()

    @property
    def esta_en_el_pasado(self):
        """Verifica si la cita está en el pasado."""
        return datetime.combine(self.fecha, self.hora_fin) < datetime.now()

    def cancelar_por_paciente(self):
        """Cancela la cita por el paciente."""
        self.estado_cita = 'cancelada_paciente'
        self.save()

    def cancelar_por_profesional(self):
        """Cancela la cita por el profesional."""
        self.estado_cita = 'cancelada_profesional'
        self.save()

    def confirmar(self):
        """Confirma la cita por el profesional."""
        self.estado_cita = 'confirmada'
        self.save()
        
    def completada(self):
        """Completada la cita por el profesional."""
        self.estado_cita = 'completada'
        self.save()    

    class Meta:
        ordering = ['fecha']
        indexes = [
            models.Index(fields=['fecha']),
            models.Index(fields=['estado_cita']),
        ]

sistema_salud/citas/forms.py
# citas/forms.py
from django import forms
from .models import Cita, CustomUser
from django.core.exceptions import ValidationError
from datetime import date

class CitaForm(forms.ModelForm):
    hora_inicio = forms.ChoiceField(
        choices=[],
        widget=forms.Select(attrs={
            'class': 'mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500'
        })
    )
    
    class Meta:
        model = Cita
        fields = ['fecha', 'profesional', 'hora_inicio', 'descripcion']
        widgets = {
            'fecha': forms.DateInput(attrs={
                'type': 'date',
                'class': 'mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500'
            }),
            'profesional': forms.Select(attrs={
                'class': 'mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500'
            }),
            'descripcion': forms.Textarea(attrs={
                'class': 'mt-1 block w-full bg-gray-100 border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500',
                'rows': 3,
                'placeholder': 'Describa brevemente el motivo de la cita',
            }),
        }

    def __init__(self, *args, horas_disponibles=None, profesional=None, fecha=None, **kwargs):
        """
        Inicializa el formulario con horarios dinámicos y profesionales disponibles.
        """
        super().__init__(*args, **kwargs)

        # Filtra los profesionales disponibles en el campo 'profesional'
        self.fields['profesional'].queryset = CustomUser.objects.filter(user_type='profesional')

        # Maneja los horarios
        self._set_horarios_disponibles(horas_disponibles, profesional, fecha)

    def _set_horarios_disponibles(self, horas_disponibles, profesional, fecha):
        """
        Configura las opciones de 'hora_inicio' según los horarios disponibles y ocupados.
        """
        # Si no se proporcionaron horarios base, usa una lista vacía
        horarios_base = horas_disponibles or []
        horarios_ocupados = []

        if profesional and fecha:
            # Obtiene los horarios ocupados del profesional en esa fecha
            horarios_ocupados = Cita.objects.filter(
                profesional=profesional,
                fecha=fecha
            ).exclude(estado_cita__in=['cancelada_paciente', 'cancelada_profesional']) \
             .values_list('hora_inicio', flat=True)

        # Genera las opciones con etiquetas indicativas
        self.fields['hora_inicio'].choices = [
            (hora, f"{hora} (ocupado)" if hora in horarios_ocupados else hora)
            for hora in horarios_base
        ]

    def clean_fecha(self):
        """
        Valida que la fecha no sea en el pasado.
        """
        fecha = self.cleaned_data.get('fecha')
        if fecha and fecha < date.today():
            raise ValidationError("La fecha no puede ser en el pasado.")
        return fecha
    
class BloquearHorarioForm(forms.ModelForm):
    hora_inicio = forms.ChoiceField(choices=[], widget=forms.Select(attrs={'class': 'form-control'}))
    
    class Meta:
        model = Cita
        fields = ['fecha', 'hora_inicio', 'es_bloqueado']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'es_bloqueado': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def __init__(self, *args, **kwargs):
        horas_disponibles = kwargs.pop('horas_disponibles', [])
        super().__init__(*args, **kwargs)
        self.fields['hora_inicio'].choices = [(hora, hora) for hora in horas_disponibles]

sistema_salud/citas/views.py
# citas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Cita,CustomUser
from .forms import CitaForm, BloquearHorarioForm
from datetime import datetime
from django.http import JsonResponse



# Paciente: Ver y agendar citas
@login_required
def lista_citas_paciente(request):
    citas = Cita.objects.filter(paciente=request.user)
    return render(request, 'citas/lista_citas_paciente.html', {'citas': citas})

# Profesional: Ver citas asignadas
@login_required
def lista_citas_profesional(request):
    today = timezone.now().date()
    tomorrow = today + timezone.timedelta(days=1)

    # Filtrar las citas del profesional actual
    citas_hoy = Cita.objects.filter(profesional=request.user, fecha=today).order_by('hora_inicio')
    citas_manana = Cita.objects.filter(
    profesional=request.user,
    fecha=tomorrow,
    estado_cita__in=['pendiente','confirmada']
    ).order_by('hora_inicio')
    proximas_citas = Cita.objects.filter(profesional=request.user, fecha__gt=today, estado_cita='confirmada')
    cantidad_citas = proximas_citas.count() 
    print(cantidad_citas)
    citas_canceladas = Cita.objects.filter(profesional=request.user, estado_cita__in=['cancelada_paciente','cancelada_paciente'])
    

    context = {
        'citas_hoy': citas_hoy,
        'citas_manana': citas_manana,
        'cantidad_citas': cantidad_citas,
        'citas_canceladas':citas_canceladas,
        'proximas_citas':proximas_citas
    }
    return render(request, 'citas/lista_citas_profesional.html', context)

def citas_view(request):
    

    # Filtrar citas activas (futuras)
    citas_activas = Cita.objects.filter(profesional=request.user, fecha__gte=datetime.now(), estado_cita="confirmada")

    # Segregar citas activas por estado
    citas_pendientes = Cita.objects.filter(estado_cita="pendiente")  # Aún no confirmadas
    citas_confirmadas = Cita.objects.filter(fecha__gte=datetime.now(),estado_cita="confirmada")  # Confirmadas por el usuario o sistema

    # Citas pasadas
    citas_pasadas = Cita.objects.filter(profesional=request.user, fecha__lt=datetime.now())
    citas_completadas = Cita.objects.filter(estado_cita="completada")
    citas_canceladas = Cita.objects.filter(profesional=request.user, estado_cita__in=['cancelada_paciente','cancelada_paciente'])

    context = {
        'citas_pasadas':citas_pasadas,
        'citas_pendientes': citas_pendientes,
        'citas_confirmadas': citas_confirmadas,
        'citas_completadas': citas_completadas,
        'citas_canceladas': citas_canceladas,
    }
    return render(request, 'citas/citas.html', context)


def agendar_cita(request):
    horas_disponibles = ['08:00', '08:30', '09:00', '09:30', '10:00', '11:00', '11:30', '12:00', '12:30', '14:00']

    # Obtener el ID del profesional desde los parámetros GET
    profesional_id = request.GET.get('profesional_id')
    profesional = None
    fecha = None

    # Si se recibe un ID de profesional, obtenemos el profesional desde la base de datos
    if profesional_id:
        profesional = get_object_or_404(CustomUser, id=profesional_id, user_type='profesional')

    # Procesar el formulario cuando se envía con POST
    if request.method == 'POST':
        form = CitaForm(request.POST, horas_disponibles=horas_disponibles, profesional=profesional, fecha=request.POST.get('fecha'))
        
        # Validar el formulario
        if form.is_valid():
            # Obtener los datos del formulario
            cita_data = form.cleaned_data
            cita_profesional = cita_data['profesional']
            cita_fecha = cita_data['fecha']
            cita_hora_inicio = cita_data['hora_inicio']

            # Verificar si ya existe una cita para ese profesional, fecha y hora
            if Cita.objects.filter(profesional=cita_profesional,
                                   fecha=cita_fecha,
                                   hora_inicio=cita_hora_inicio).exclude(estado_cita__in=['cancelada_paciente', 'cancelada_profesional']).exists():
                form.add_error('hora_inicio', 'Esta hora ya está ocupada por otra cita.')
            else:
                # Si no hay conflicto, guardamos la cita
                cita = form.save(commit=False)
                cita.paciente = request.user
                cita.estado_cita = 'pendiente'

                # Asignar duración predeterminada si no se pasa
                if not cita.duracion:
                    cita.duracion = 30

                cita.save()
                return redirect('citas:lista_citas_paciente')
    else:
        # Si el método no es POST, inicializamos el formulario con la fecha recibida
        fecha = request.GET.get('fecha')
        form = CitaForm(
            horas_disponibles=horas_disponibles,
            initial={'profesional': profesional} if profesional else None,
            fecha=fecha
        )

    return render(request, 'citas/agendar_cita.html', {'form': form, 'horas_disponibles': horas_disponibles})




@login_required
def cambiar_estado_cita(request, cita_id, nuevo_estado):
    cita = get_object_or_404(Cita, id=cita_id)

    if nuevo_estado == 'confirmada':
        cita.confirmar()
    elif nuevo_estado == 'completada':
        cita.completada()    
    elif nuevo_estado == 'cancelada_paciente':
        cita.cancelar_por_paciente()
    elif nuevo_estado == 'cancelada_profesional':
        cita.cancelar_por_profesional()
    
    # Redirigir al usuario de vuelta a la lista de citas
    return redirect('citas:lista_citas_paciente' if request.user == cita.paciente else 'citas:lista_citas_profesional')

@login_required
def bloquear_horario(request):
    if request.method == 'POST':
        form = BloquearHorarioForm(request.POST)
        if form.is_valid():
            bloqueo = form.save(commit=False)
            bloqueo.profesional = request.user  # Asumimos que el usuario autenticado es el profesional
            bloqueo.es_bloqueado = True
            bloqueo.save()
            return redirect('profesional_dashboard')  # Redirige al dashboard del profesional o donde prefieras
    else:
        form = BloquearHorarioForm()
    
    return render(request, 'citas/bloquear_horario.html', {'form': form})

sistema_salud/templates/citas/bloquear_horario.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card shadow p-4">
        <h2 class="card-title text-center mb-4">Bloquear Horario</h2>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="form-group mb-3">
                <label for="id_fecha" class="form-label">Fecha:</label>
                {{ form.fecha }}
            </div>
            <div class="form-group mb-3">
                <label for="id_hora_inicio" class="form-label">Hora:</label>
                {{ form.hora_inicio }}
            </div>
            <div class="form-group mb-3 form-check">
                {{ form.es_bloqueado }}
                <label for="id_es_bloqueado" class="form-check-label">Bloquear este horario</label>
            </div>
            <button type="submit" class="btn btn-danger w-100 mt-4">Bloquear Horario</button>
        </form>
    </div>
</div>
{% endblock %}

sistema_salud/templates/citas/lista_citas_paciente.html
<!-- citas/templates/citas/lista_citas_paciente.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto mt-6 p-6 bg-white shadow-lg rounded-lg">
    <h2 class="text-4xl font-bold text-blue-500 mb-6">
        Mis Citas
    </h2>

    <div class="mb-4">
        <a href="{% url 'citas:agendar_cita' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded inline-flex items-center">
            <i class="fas fa-calendar-plus mr-2"></i> Agendar Nueva Cita
        </a>
    </div>

    <div class="overflow-x-auto rounded-lg shadow-md">
        <table class="min-w-full bg-white">
            <thead>
                <tr class="bg-gray-200 text-gray-700 uppercase text-sm leading-normal">
                    <th class="py-3 px-6 text-left">Profesional de la Salud</th>
                    <th class="py-3 px-6 text-left">Especialidad</th>
                    <th class="py-3 px-6 text-left">Fecha</th>
                    <th class="py-3 px-6 text-left">Hora de Inicio</th>
                    <th class="py-3 px-6 text-left">Sintoma</th>
                    <th class="py-3 px-6 text-left">Estado</th>
                    <th class="py-3 px-6 text-center">Acciones</th>
                </tr>
            </thead>
            <tbody class="text-gray-600 text-sm font-light">
                {% for cita in citas %}
                    <tr class="border-b border-gray-200 hover:bg-gray-100">
                        <td class="py-2 px-4 border-b"><span class="inline-block bg-green-500 text-white rounded-full px-3 py-1">{{ cita.profesional.full_name }}</span></td>
                        <td class="py-2 px-4 border-b"><span class="inline-block bg-blue-500 text-white rounded-full px-3 py-1">{{ cita.profesional.specialties }}</span></td>
                        <td class="py-3 px-6 text-left">
                            <span class="text-blue-800 font-semibold">{{ cita.fecha|date:"d M Y" }}</span>
                        </td>
                        <td class="py-3 px-6 text-left">
                            <span class="text-blue-800 font-semibold">{{ cita.hora_inicio }}</span>
                        </td>
                        <td class="py-3 px-6 text-left">
                            <span class="text-blue-800 font-semibold">{{ cita.descripcion }}</span>
                        </td>
                        <td class="py-3 px-6 text-left">
                            {% if cita.estado_cita == 'confirmada' %}
                                <span class="inline-block bg-green-200 text-green-800 rounded-full px-3 py-1">Confirmada</span>
                            {% elif cita.estado_cita == 'cancelada_paciente' %}
                                <span class="inline-block bg-red-200 text-red-800 rounded-full px-3 py-1">Cancelada por el Paciente</span>
                            {% elif cita.estado_cita == 'cancelada_profesional' %}
                                <span class="inline-block bg-red-200 text-red-800 rounded-full px-3 py-1">Cancelada por el Profesional</span>
                            {% elif cita.estado_cita == 'completada' %}
                                <span class="inline-block bg-blue-500 text-white rounded-full px-3 py-1">Completada</span>
                            {% else %}
                                <span class="inline-block bg-yellow-200 text-yellow-800 rounded-full px-3 py-1">Pendiente</span>
                            {% endif %}
                        </td>
                        <td class="py-3 px-6 text-center">
                            {% if cita.estado_cita  == 'pendiente' %}
                                <a href="{% url 'citas:cambiar_estado_cita' cita.id 'cancelada_paciente' %}" class="bg-red-500 hover:bg-red-600 text-white py-1 px-3 rounded text-sm">Cancelar</a>
                            {% elif cita.estado_cita == 'confirmada' %}
                            <a href="{% url 'citas:cambiar_estado_cita' cita.id 'cancelada_paciente' %}" class="bg-red-500 hover:bg-red-600 text-white py-1 px-3 rounded text-sm">Cancelar</a>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="7" class="py-4 text-center text-gray-500">No tienes citas asignadas</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

sistema_salud/templates/citas/lista_citas_profesional.html
{% extends 'base.html' %}

{% block content %}
<div class="container mx-auto mt-10 p-6 bg-white shadow-lg rounded-lg">
    <h2 class="text-4xl font-bold text-blue-600 mb-6">Citas Asignadas</h2>

    <!-- Dashboard de Citas -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div class="bg-blue-500 text-white p-6 rounded-lg shadow flex items-center">
            <i class="fas fa-calendar-day text-5xl mr-4"></i>
            <div>
                <h5 class="font-bold text-lg">Citas de Hoy</h5>
                <p class="text-2xl font-semibold">{{ citas_hoy.count }}</p>
            </div>
        </div>
        <div class="bg-yellow-500 text-white p-6 rounded-lg shadow flex items-center">
            <i class="fas fa-calendar-plus text-5xl mr-4"></i>
            <div>
                <h5 class="font-bold text-lg">Citas de Mañana</h5>
                <p class="text-2xl font-semibold">{{ citas_manana.count }}</p>
            </div>
        </div>
        <div class="bg-green-500 text-white p-6 rounded-lg shadow flex items-center">
            <i class="fas fa-calendar-check text-5xl mr-4"></i>
            <div>
                <h5 class="font-bold text-lg">Próximas Citas</h5>
                <p class="text-2xl font-semibold">{{ proximas_citas.count }}</p>
            </div>
        </div>
        <div class="bg-red-500 text-white p-6 rounded-lg shadow flex items-center">
            <i class="fas fa-calendar-times text-5xl mr-4"></i>
            <div>
                <h5 class="font-bold text-lg">Citas Canceladas</h5>
                <p class="text-2xl font-semibold">{{ citas_canceladas.count }}</p>
            </div>
        </div>
    </div>

    <!-- Citas de Hoy -->
    <div class="mt-6">
        <h3 class="text-2xl font-semibold mb-2">Citas de Hoy</h3>
        <div class="overflow-x-auto rounded-lg shadow-md">
            <table class="min-w-full bg-white">
                <thead>
                    <tr class="bg-gray-200 text-gray-700 uppercase text-sm leading-normal">
                        <th class="py-3 px-6 text-left">Paciente</th>
                        <th class="py-3 px-6 text-left">Fecha</th>
                        <th class="py-3 px-6 text-left">Hora de Inicio</th>
                        <th class="py-3 px-6 text-left">Síntomas</th>
                        <th class="py-3 px-6 text-left">Estado</th>
                        <th class="py-3 px-6 text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody class="text-gray-700 text-sm divide-y divide-gray-200">
                    {% for cita in citas_hoy %}
                    {% if cita.estado_cita == 'pendiente' or cita.estado_cita == 'confirmada' or cita.estado_cita == 'completada'%}
                    <tr class="hover:bg-gray-100">
                        <td class="py-3 px-6 text-left font-medium text-gray-700">{{ cita.paciente.full_name }}</td>
                        <td class="py-3 px-6 text-left">{{ cita.fecha|date:"d M Y" }}</td>
                        <td class="py-3 px-6 text-left">{{ cita.hora_inicio }}</td>
                        <td class="py-3 px-6 text-left">{{ cita.descripcion }}</td>
                        <td class="py-3 px-6 text-left">
                            {% if cita.estado_cita == 'confirmada' %}
                                <span class="bg-green-200 text-green-800 rounded-full px-3 py-1">Confirmada</span>
                            
                            {% else %}
                                <span class="bg-yellow-200 text-yellow-800 rounded-full px-3 py-1">Pendiente</span>
                            {% endif %}
                        </td>
                        <td class="py-3 px-6 text-center">
                            {% if cita.estado_cita  == 'pendiente' %}
                                <a href="{% url 'citas:cambiar_estado_cita' cita.id 'cancelada_profesional' %}" class="bg-red-500 hover:bg-red-600 text-white py-1 px-3 rounded text-sm">Cancelar</a>
                                <a href="{% url 'citas:cambiar_estado_cita' cita.id 'confirmada' %}" class="bg-green-500 hover:bg-blue-600 text-white py-1 px-3 rounded text-sm">Confirmar</a>
                            {% elif cita.estado_cita == 'confirmada' %}
                            <a href="{% url 'citas:cambiar_estado_cita' cita.id 'cancelada_profesional' %}" class="bg-red-500 hover:bg-red-600 text-white py-1 px-3 rounded text-sm">Cancelar</a>
                            <a href="{% url 'citas:cambiar_estado_cita' cita.id 'completada' %}" class="bg-blue-500 hover:bg-green-600 text-white py-1 px-3 rounded text-sm">Completada</a>

                            
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                    {% empty %}
                    <tr>
                        <td colspan="6" class="py-4 text-center text-gray-500">No hay citas programadas para hoy.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

     <!-- Citas de Mañana -->
     <div class="mt-6">
        <h3 class="text-2xl font-semibold mb-2">Citas de Mañana</h3>
        <div class="overflow-x-auto rounded-lg shadow-md">
            <table class="table-auto w-full border-collapse border border-gray-300 rounded-lg shadow-lg">
                <thead class="bg-blue-500 text-white text-left">
                    <tr >
                        <th class="py-3 px-6 text-left ">Paciente</th>
                        <th class="py-3 px-6 text-left">Fecha</th>
                        <th class="py-3 px-6 text-left">Hora de Inicio</th>
                        <th class="py-3 px-6 text-left">Síntomas</th>
                        <th class="py-3 px-6 text-left">Estado</th>
                        <th class="py-3 px-6 text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200">
                    {% for cita in citas_manana %}
                    {% if cita.estado_cita == 'pendiente' or cita.estado_cita == 'confirmada' %}
                    <tr class="hover:bg-gray-100 transition-colors">
                        <td class="py-3 px-6 text-left font-medium text-gray-700">{{ cita.paciente.full_name }}</td>
                        <td class="py-3 px-6 text-left text-gray-600">{{ cita.fecha|date:"d M Y" }}</td>
                        <td class="py-3 px-6 text-left text-gray-600">{{ cita.hora_inicio }}</td>
                        <td class="py-3 px-6 text-left text-gray-500 italic">{{ cita.descripcion }}</td>
                        <td class="py-3 px-6 text-left">
                            {% if cita.estado_cita == 'confirmada' %}
                                <span class="bg-green-200 text-green-800 rounded-full px-3 py-1">Confirmada</span>
                            {% else %}
                                <span class="bg-yellow-200 text-yellow-800 rounded-full px-3 py-1">Pendiente</span>
                            {% endif %}
                        </td>
                        <td class="py-3 px-6 text-center">
                            {% if cita.estado_cita  == 'pendiente' %}
                                <a href="{% url 'citas:cambiar_estado_cita' cita.id 'cancelada_profesional' %}" class="bg-red-500 hover:bg-red-600 text-white py-1 px-3 rounded text-sm">Cancelar</a>
                                <a href="{% url 'citas:cambiar_estado_cita' cita.id 'confirmada' %}" class="bg-green-500 hover:bg-blue-600 text-white py-1 px-3 rounded text-sm">Confirmar</a>
                            {% elif cita.estado_cita == 'confirmada' %}
                            <a href="{% url 'citas:cambiar_estado_cita' cita.id 'cancelada_profesional' %}" class="bg-red-500 hover:bg-red-600 text-white py-1 px-3 rounded text-sm">Cancelar</a>
                            <a href="{% url 'citas:cambiar_estado_cita' cita.id 'completada' %}" class="bg-blue-500 hover:bg-green-600 text-white py-1 px-3 rounded text-sm">Completada</a>

                            
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                    {% empty %}
                    <tr>
                        <td colspan="6" class="py-4 text-center text-gray-500">No hay citas programadas para hoy.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Citas Canceladas -->
    <div class="mt-6">
        <h3 class="text-2xl font-semibold mb-2">Citas Canceladas</h3>
        <div class="overflow-x-auto rounded-lg shadow-md">
            <table class="min-w-full bg-white">
                <thead>
                    <tr class="bg-gray-200 text-gray-700 uppercase text-sm leading-normal">
                        <th class="py-3 px-6 text-left">Paciente</th>
                        <th class="py-3 px-6 text-left">Fecha</th>
                        <th class="py-3 px-6 text-left">Hora de Inicio</th>
                        <th class="py-3 px-6 text-left">Síntomas</th>
                        <th class="py-3 px-6 text-left">Cancelada por</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-sm font-light">
                    {% for cita in citas_canceladas %}
                    <tr class="border-b border-gray-200 hover:bg-gray-100">
                        <td class="py-3 px-6 text-left">{{ cita.paciente.full_name }}</td>
                        <td class="py-3 px-6 text-left">{{ cita.fecha|date:"d M Y" }}</td>
                        <td class="py-3 px-6 text-left">{{ cita.hora_inicio }}</td>
                        <td class="py-3 px-6 text-left">{{ cita.descripcion }}</td>
                        <td class="py-3 px-6 text-left">
                            {% if cita.estado_cita == 'cancelada_paciente' %}
                                Paciente
                            {% else %}
                                Profesional
                            {% endif %}
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="py-4 text-center text-gray-500">No hay citas canceladas.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}